//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 LeftStick
        {
            get
            {
                return SteamVR_Actions.default_LeftStick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightStick
        {
            get
            {
                return SteamVR_Actions.default_RightStick;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftClick
        {
            get
            {
                return SteamVR_Actions.default_LeftClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightClick
        {
            get
            {
                return SteamVR_Actions.default_RightClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean Button_A
        {
            get
            {
                return SteamVR_Actions.default_Button_A;
            }
        }
        
        public virtual SteamVR_Action_Boolean Button_B
        {
            get
            {
                return SteamVR_Actions.default_Button_B;
            }
        }
        
        public virtual SteamVR_Action_Boolean Button_X
        {
            get
            {
                return SteamVR_Actions.default_Button_X;
            }
        }
        
        public virtual SteamVR_Action_Boolean Button_Y
        {
            get
            {
                return SteamVR_Actions.default_Button_Y;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTrigger
        {
            get
            {
                return SteamVR_Actions.default_LeftTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTrigger
        {
            get
            {
                return SteamVR_Actions.default_RightTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftGrad
        {
            get
            {
                return SteamVR_Actions.default_LeftGrad;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightGrad
        {
            get
            {
                return SteamVR_Actions.default_RightGrad;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftPose
        {
            get
            {
                return SteamVR_Actions.default_LeftPose;
            }
        }
        
        public virtual SteamVR_Action_Pose RightPose
        {
            get
            {
                return SteamVR_Actions.default_RightPose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton LeftSkeleton
        {
            get
            {
                return SteamVR_Actions.default_LeftSkeleton;
            }
        }
        
        public virtual SteamVR_Action_Skeleton RightSkeleton
        {
            get
            {
                return SteamVR_Actions.default_RightSkeleton;
            }
        }
        
        public virtual SteamVR_Action_Vibration Hattic
        {
            get
            {
                return SteamVR_Actions.default_Hattic;
            }
        }
    }
}
