//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Vector2 p_default_LeftStick;
        
        private static SteamVR_Action_Vector2 p_default_RightStick;
        
        private static SteamVR_Action_Boolean p_default_LeftClick;
        
        private static SteamVR_Action_Boolean p_default_RightClick;
        
        private static SteamVR_Action_Boolean p_default_Button_A;
        
        private static SteamVR_Action_Boolean p_default_Button_B;
        
        private static SteamVR_Action_Boolean p_default_Button_X;
        
        private static SteamVR_Action_Boolean p_default_Button_Y;
        
        private static SteamVR_Action_Boolean p_default_LeftTrigger;
        
        private static SteamVR_Action_Boolean p_default_RightTrigger;
        
        private static SteamVR_Action_Boolean p_default_LeftGrad;
        
        private static SteamVR_Action_Boolean p_default_RightGrad;
        
        private static SteamVR_Action_Pose p_default_LeftPose;
        
        private static SteamVR_Action_Pose p_default_RightPose;
        
        private static SteamVR_Action_Skeleton p_default_LeftSkeleton;
        
        private static SteamVR_Action_Skeleton p_default_RightSkeleton;
        
        private static SteamVR_Action_Vibration p_default_Hattic;
        
        public static SteamVR_Action_Vector2 default_LeftStick
        {
            get
            {
                return SteamVR_Actions.p_default_LeftStick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_RightStick
        {
            get
            {
                return SteamVR_Actions.p_default_RightStick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean default_LeftClick
        {
            get
            {
                return SteamVR_Actions.p_default_LeftClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_RightClick
        {
            get
            {
                return SteamVR_Actions.p_default_RightClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Button_A
        {
            get
            {
                return SteamVR_Actions.p_default_Button_A.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Button_B
        {
            get
            {
                return SteamVR_Actions.p_default_Button_B.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Button_X
        {
            get
            {
                return SteamVR_Actions.p_default_Button_X.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Button_Y
        {
            get
            {
                return SteamVR_Actions.p_default_Button_Y.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_LeftTrigger
        {
            get
            {
                return SteamVR_Actions.p_default_LeftTrigger.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_RightTrigger
        {
            get
            {
                return SteamVR_Actions.p_default_RightTrigger.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_LeftGrad
        {
            get
            {
                return SteamVR_Actions.p_default_LeftGrad.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_RightGrad
        {
            get
            {
                return SteamVR_Actions.p_default_RightGrad.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_LeftPose
        {
            get
            {
                return SteamVR_Actions.p_default_LeftPose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Pose default_RightPose
        {
            get
            {
                return SteamVR_Actions.p_default_RightPose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_LeftSkeleton
        {
            get
            {
                return SteamVR_Actions.p_default_LeftSkeleton.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_RightSkeleton
        {
            get
            {
                return SteamVR_Actions.p_default_RightSkeleton.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Hattic
        {
            get
            {
                return SteamVR_Actions.p_default_Hattic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_LeftStick,
                    SteamVR_Actions.default_RightStick,
                    SteamVR_Actions.default_LeftClick,
                    SteamVR_Actions.default_RightClick,
                    SteamVR_Actions.default_Button_A,
                    SteamVR_Actions.default_Button_B,
                    SteamVR_Actions.default_Button_X,
                    SteamVR_Actions.default_Button_Y,
                    SteamVR_Actions.default_LeftTrigger,
                    SteamVR_Actions.default_RightTrigger,
                    SteamVR_Actions.default_LeftGrad,
                    SteamVR_Actions.default_RightGrad,
                    SteamVR_Actions.default_LeftPose,
                    SteamVR_Actions.default_RightPose,
                    SteamVR_Actions.default_LeftSkeleton,
                    SteamVR_Actions.default_RightSkeleton,
                    SteamVR_Actions.default_Hattic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_LeftStick,
                    SteamVR_Actions.default_RightStick,
                    SteamVR_Actions.default_LeftClick,
                    SteamVR_Actions.default_RightClick,
                    SteamVR_Actions.default_Button_A,
                    SteamVR_Actions.default_Button_B,
                    SteamVR_Actions.default_Button_X,
                    SteamVR_Actions.default_Button_Y,
                    SteamVR_Actions.default_LeftTrigger,
                    SteamVR_Actions.default_RightTrigger,
                    SteamVR_Actions.default_LeftGrad,
                    SteamVR_Actions.default_RightGrad,
                    SteamVR_Actions.default_LeftPose,
                    SteamVR_Actions.default_RightPose,
                    SteamVR_Actions.default_LeftSkeleton,
                    SteamVR_Actions.default_RightSkeleton};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Hattic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Hattic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_LeftPose,
                    SteamVR_Actions.default_RightPose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_LeftClick,
                    SteamVR_Actions.default_RightClick,
                    SteamVR_Actions.default_Button_A,
                    SteamVR_Actions.default_Button_B,
                    SteamVR_Actions.default_Button_X,
                    SteamVR_Actions.default_Button_Y,
                    SteamVR_Actions.default_LeftTrigger,
                    SteamVR_Actions.default_RightTrigger,
                    SteamVR_Actions.default_LeftGrad,
                    SteamVR_Actions.default_RightGrad};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_LeftStick,
                    SteamVR_Actions.default_RightStick};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_LeftSkeleton,
                    SteamVR_Actions.default_RightSkeleton};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_LeftStick,
                    SteamVR_Actions.default_RightStick,
                    SteamVR_Actions.default_LeftClick,
                    SteamVR_Actions.default_RightClick,
                    SteamVR_Actions.default_Button_A,
                    SteamVR_Actions.default_Button_B,
                    SteamVR_Actions.default_Button_X,
                    SteamVR_Actions.default_Button_Y,
                    SteamVR_Actions.default_LeftTrigger,
                    SteamVR_Actions.default_RightTrigger,
                    SteamVR_Actions.default_LeftGrad,
                    SteamVR_Actions.default_RightGrad};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_LeftStick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/LeftStick")));
            SteamVR_Actions.p_default_RightStick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/RightStick")));
            SteamVR_Actions.p_default_LeftClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/LeftClick")));
            SteamVR_Actions.p_default_RightClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/RightClick")));
            SteamVR_Actions.p_default_Button_A = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Button_A")));
            SteamVR_Actions.p_default_Button_B = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Button_B")));
            SteamVR_Actions.p_default_Button_X = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Button_X")));
            SteamVR_Actions.p_default_Button_Y = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Button_Y")));
            SteamVR_Actions.p_default_LeftTrigger = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/LeftTrigger")));
            SteamVR_Actions.p_default_RightTrigger = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/RightTrigger")));
            SteamVR_Actions.p_default_LeftGrad = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/LeftGrad")));
            SteamVR_Actions.p_default_RightGrad = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/RightGrad")));
            SteamVR_Actions.p_default_LeftPose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/LeftPose")));
            SteamVR_Actions.p_default_RightPose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/RightPose")));
            SteamVR_Actions.p_default_LeftSkeleton = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/LeftSkeleton")));
            SteamVR_Actions.p_default_RightSkeleton = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/RightSkeleton")));
            SteamVR_Actions.p_default_Hattic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Hattic")));
        }
    }
}
